server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:1514
      idle_timeout: 60s
      label_structured_data: yes
      labels:
        job: "syslog"
    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: 'host'
  - job_name: system
    static_configs:
    - targets:
      - localhost
      labels:
        job: varlogs
        host: localhost
        __path__: /var/log/*log
  - job_name: cpb_eshop
    static_configs:
    - targets:
      - localhost
      labels:
        job: cpb_eshop
        host: localhost
        __path__: /var/cpblog/*log
  - job_name: node_red
    static_configs:
    - targets:
      - localhost
      labels:
        job: node_red
        host: localhost
        __path__: /var/nodered/node_red_logs/*/*log
